---
- name: "Converge"
  hosts: "cicd-debian-11"
  tasks:

    - name: "Include labocbz.install_redis"
      tags:
        - "labocbz.install_redis"
      vars:
        install_redis__user: "{{ inv_install_redis__user }}"
        install_redis__group: "{{ inv_install_redis__group }}"
        install_redis__bind: "{{ inv_install_redis__bind }}"
        install_redis__port: "{{ inv_install_redis__port }}"
        install_redis__proteced_mode: "{{ inv_install_redis__proteced_mode }}"
        install_redis__loglevel: "{{ inv_install_redis__loglevel }}"
        install_redis__requirepass: "{{ inv_install_redis__requirepass }}"
        install_redis__cluster: "{{ inv_install_redis__cluster }}"
        install_redis__cluster_port: "{{ inv_install_redis__cluster_port }}"
        install_redis__initial_master: "{{ inv_install_redis__initial_master }}"
        install_redis__initial_mastername: "{{ inv_install_redis__initial_mastername }}"
        install_redis__sentinel_port: "{{ inv_install_redis__sentinel_port }}"
        install_redis__log_path: "{{ inv_install_redis__log_path }}"
        install_redis__logfile: "{{ inv_install_redis__logfile }}"
        install_redis__ssl: "{{ inv_install_redis__ssl }}"
        install_redis__ssl_domain: "{{ inv_install_redis__ssl_domain }}"
        install_redis__ssl_path: "{{ inv_install_redis__ssl_path }}"
        install_redis__ssl_key: "{{ inv_install_redis__ssl_key }}"
        install_redis__ssl_cert: "{{ inv_install_redis__ssl_cert }}"
        install_redis__ssl_client_auth: "{{ inv_install_redis__ssl_client_auth }}"
        install_redis__ssl_ca: "{{ inv_install_redis__ssl_ca }}"
      ansible.builtin.include_role:
        name: "labocbz.install_redis"
