---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-debian-11"
  gather_facts: false
  tasks:

    - name: "Verify Redis installations"
      block:
        - name: "Get Redis service current state"
          register: install_redis__service_status
          failed_when: not install_redis__service_status.status.ActiveState == 'active'
          ansible.builtin.systemd:
            name: "redis-server"

        - name: "Check Redis connectivity"
          ansible.builtin.wait_for:
            host: "{{ inventory_hostname }}"
            port: "{{ inv_install_redis__port }}"
            timeout: 120

    - name: "Verify Redis STANDALONE configurations, no auth"
      when: not(inv_install_redis__requirepass | default(false))
      block:
        - name: "Verify with no client cert, no ssl, no password"
          when: not (inv_install_redis__ssl | default(false)) and not (inv_install_redis__ssl_client_auth | default(false))
          register: install_redis__auth_result
          failed_when: install_redis__auth_result.stdout != "PONG"
          changed_when: install_redis__auth_result.rc != 0
          ansible.builtin.command: |
            redis-cli -h {{ inventory_hostname }} -p {{ inv_install_redis__port }} ping

        - name: "Verify with no client cert, yes ssl, no password"
          when: (inv_install_redis__ssl | default(false)) and not (inv_install_redis__ssl_client_auth | default(false))
          register: install_redis__auth_result
          failed_when: install_redis__auth_result.stdout != "PONG"
          changed_when: install_redis__auth_result.rc != 0
          ansible.builtin.command: |
            redis-cli --tls -h {{ inventory_hostname }} -p {{ inv_install_redis__port }} ping

        - name: "Verify with yes client cert, yes ssl, no password"
          when: (inv_install_redis__ssl | default(false)) and not (inv_install_redis__ssl_client_auth | default(false))
          register: install_redis__auth_result
          failed_when: install_redis__auth_result.stdout != "PONG"
          changed_when: install_redis__auth_result.rc != 0
          ansible.builtin.command: |
            redis-cli --cert {{ inv_install_redis__ssl_cert }} --key {{ inv_install_redis__ssl_key }} --tls -h {{ inventory_hostname }} -p {{ inv_install_redis__port }} ping

    - name: "Verify Redis STANDALONE configurations, with auth"
      when: inv_install_redis__requirepass | default(false)
      block:
        - name: "Verify with no client cert, no ssl, yes password"
          when: not (inv_install_redis__ssl | default(false)) and not (inv_install_redis__ssl_client_auth | default(false))
          register: install_redis__auth_result
          failed_when: install_redis__auth_result.stdout != "PONG"
          changed_when: install_redis__auth_result.rc != 0
          ansible.builtin.command: |
            redis-cli -a {{ inv_install_redis__requirepass }} -h {{ inventory_hostname }} -p {{ inv_install_redis__port }} --no-auth-warning ping

        - name: "Verify with no client cert, yes ssl, yes password"
          when: (inv_install_redis__ssl | default(false)) and not (inv_install_redis__ssl_client_auth | default(false))
          register: install_redis__auth_result
          failed_when: install_redis__auth_result.stdout != "PONG"
          changed_when: install_redis__auth_result.rc != 0
          ansible.builtin.command: |
            redis-cli --tls -a {{ inv_install_redis__requirepass }} -h {{ inventory_hostname }} -p {{ inv_install_redis__port }} --no-auth-warning ping

        - name: "Verify with yes client cert, yes ssl, yes password"
          when: (inv_install_redis__ssl | default(false)) and (inv_install_redis__ssl_client_auth | default(false))
          register: install_redis__auth_result
          failed_when: install_redis__auth_result.stdout != "PONG"
          changed_when: install_redis__auth_result.rc != 0
          ansible.builtin.command: |
            redis-cli --cert {{ inv_install_redis__ssl_cert }} --key {{ inv_install_redis__ssl_key }} --tls -a {{ inv_install_redis__requirepass }} -h {{ inventory_hostname }} -p {{ inv_install_redis__port }} --no-auth-warning ping
